### ISSUE TITLE
rmotifx+ggseqlogo

### ISSUE THREAD

**Issue by kamalmdmostafa** [omarwagih/rmotifx#10]
Hi Omar, 

Thanks so much for saving the motif-x in this platform since the original site went down. It is not an issue more of a request (suggestion). 

Is it possible to combine the ggeseqlogo with the rmotifx? The output results of the motifs in the same package will be a great combination. 

Kamal

**Comment by omarwagih** [comment]
I've been meaning to do something like this for a while, but don't have much time now. It's fairly straight forward to do but if you have a pull request if you have an implementation you want to contribute!
