### ISSUE TITLE
Can rmotifx generate a sequence logo for each motif?

### ISSUE THREAD

**Issue by zhanghao-njmu** [omarwagih/rmotifx#3]
Can rmotifx generate a sequence logo for each motif?
I see that it has just one function motifx(). 
However, a plotting function and a listing function that reporting sequence in each motif is necessary for downstream analysis.

**Comment by omarwagih** [comment]
You're going to need to give a little bit more detail on what you're trying to achieve.

**Comment by zhanghao-njmu** [comment]
For example, if we input some pre-aligned sequences and then get several motifs, more often than not we want to know the amino acid frequency of each position and create a sequence logo. This needs a detailed matching information at least, that which pre-aligned sequence can match the motif other than a single frequency of sequences matching this motif.
Thank you.

**Comment by omarwagih** [comment]
You can use `ggseqlogo` to plot sequence logos. https://github.com/omarwagih/ggseqlogo
